# Operasi Matematika & Numpy

In [1]:
import numpy as np

### Pengenalan Array

In [2]:
#1D array
a = np.array([4, 3, 5, 7])
print('banyaknya entry = ', a.size)
print('dimensi array = ', a.ndim)
print('ukuran array = ', a.shape)

banyaknya entry =  4
dimensi array =  1
ukuran array =  (4,)


In [3]:
#Slicing
a[1:]

array([3, 5, 7])

In [4]:
print('a[1:3] = ', a[1:3])
print('a[:3] = ', a[:3])

a[1:3] =  [3 5]
a[:3] =  [4 3 5]


In [5]:
#2D Array (Matriks)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Latihan-2 (2D array)

In [6]:
b = np.array([21, 7, 20, 10])
print('banyaknya entry = ',b.size)
print('dimensi array = ',b.ndim)
print('ukuran array = ',b.shape)

banyaknya entry =  4
dimensi array =  1
ukuran array =  (4,)


In [7]:
B = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

In [8]:
#Slicing
print('baris ke-2 = ', B[1])
print('entry ke-2 & 3 baris ke-2 = ', B[1, 1:])
print('entry pertama & 2 kolom ke-2 = ', B[:2, 1])

baris ke-2 =  [14 15 16]
entry ke-2 & 3 baris ke-2 =  [15 16]
entry pertama & 2 kolom ke-2 =  [12 15]


### Latihan-3 (Slicing)

In [9]:
C = np.array([[21, 2, 23], [24, 25, 26], [27, 28, 29]])
print(C)

[[21  2 23]
 [24 25 26]
 [27 28 29]]


In [10]:
# Lengkapi kodingan berikut
print('baris ke-3 = ',C[2])
print('entry ke-1 & 2 baris ke-3 = ',C[2,0:-1])
print('entry ke-2 & 3 kolom ke-3 = ',C[-2:,2])

baris ke-3 =  [27 28 29]
entry ke-1 & 2 baris ke-3 =  [27 28]
entry ke-2 & 3 kolom ke-3 =  [26 29]


output jawaban: baris ke-3 = [27 28 29]

entry ke-1 & 2 baris ke-3 = [27 28]

entry ke-2 & 3 kolom ke-3 = [26 29]

### Operasi Matematika di Numpy

In [11]:
D = A*A
print('perkalian antar entry = ')
print(D)

perkalian antar entry = 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [12]:
print('perkalian matriks = ')
print(np.matmul(A,A))

perkalian matriks = 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Bisa dilihat perbedaan perkalian antar entry dan perkalian matriks biasa?

In [13]:
print('determinan matriks A = ', np.linalg.det(A))
print('determinan matriks C = ', np.linalg.det(D))

determinan matriks A =  -9.51619735392994e-16
determinan matriks C =  -216.00000000000006


In [14]:
print('nilai dan vektor eigen matriks A = ', np.linalg.eig(A))

nilai dan vektor eigen matriks A =  (array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [15]:
print('nilai eigen matriks A = ', np.linalg.eig(A)[0])

nilai eigen matriks A =  [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


In [16]:
print('vektor eigen matriks A = ', np.linalg.eig(A)[1])

vektor eigen matriks A =  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [17]:
e_vec = np.linalg.eig(A)[1][:, 0]
e_val = np.linalg.eig(A)[0][0]

In [18]:
e_value = e_val.real

In [19]:
print(np.matmul(A, e_vec))

[ -3.73863537  -8.46653421 -13.19443305]


In [20]:
print(e_val*e_vec)

[ -3.73863537  -8.46653421 -13.19443305]


### Latihan-4 (Operasi matriks)

In [21]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:

1. 2*A
2. 2+A
3. A+B
4. A-B
5. determinan A
6. invers dari B, simpan jadi matriks D
7. transpose D
8. nilai eigen dan vektor eigen dari A dan B

In [22]:
d = np.linalg.inv(B)

In [23]:
d = 2*A
print('perkalian antar entry = ')
print(d)

perkalian antar entry = 
[[ 2  4]
 [14 16]]


In [24]:
print(B*d)

[[ 6 20]
 [14 96]]


In [35]:
B, d

(array([[3, 5],
        [1, 6]]),
 array([[ 2,  4],
        [14, 16]]))

In [34]:
print(np.matmul(B, d))

[[ 76  92]
 [ 86 100]]


In [38]:
np.__version__

'1.20.3'

In [39]:
import math

In [40]:
math.sqrt(4) # Khusus akar 2

2.0

In [42]:
7**(1/4) # akar 4 dari 7

1.6265765616977856

In [45]:
8**(1/3) # akar 3 dari 8

2.0

In [52]:
# math.log(a, b):
# a : adalah angka yang mau dicari lognya
# b : adalah base dari log
math.log(8, 2) # 7 log 21

3.0

In [51]:
math.factorial(15)

1307674368000