# Math for AI

Hitunglah:
- 2*A
- 2+A
- A+B
- A-B
- determinan A
- invers dari B, simpan jadi matriks D
- transpose D
- nilai eigen dan vektor eigen dari A dan B

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

In [8]:
print(2 * A,"==> 2 * A") # 2 * A
print("")
print(2 + A,"==> 2 + A") # 2 + A
print("")
print(A + B,"==> A + B") # A + B
print("")
print(A - B,"==> A - B") # A - B
print("")


print('Determinan Matrik A = ',np.linalg.det(A)) # Determinan A
print("")

D = (np.linalg.inv(B)) # invers dari B, simpan jadi matriks D
print(D, "==> Matriks D (Invers dari matriks B)")
print("")

trnsps_D = np.transpose(D) # Transpose Matriks D
print(trnsps_D, "==> Transpose Matriks D")
print("")

print('Nilai eigen dari Matriks A ==>',np.linalg.eig(A)[0]) # Nilai eigen dari Matriks A[0]
print("")
print('Vektor eigen dari Matriks A ==>',np.linalg.eig(A)[1]) # Vektor eigen dari Matriks A[1]
print("")

print('Nilai eigen dari Matriks B ==>',np.linalg.eig(B)[0]) # Nilai eigen dari Matriks B[0]
print("")
print('Vektor eigen dari Matriks B ==>',np.linalg.eig(B)[1]) # Vektor eigen dari Matriks B[1]

[[ 2  4]
 [14 16]] ==> 2 * A

[[ 3  4]
 [ 9 10]] ==> 2 + A

[[ 4  7]
 [ 8 14]] ==> A + B

[[-2 -3]
 [ 6  2]] ==> A - B

Determinan Matrik A =  -6.0

[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]] ==> Matriks D (Invers dari matriks B)

[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]] ==> Transpose Matriks D

Nilai eigen dari Matriks A = [-0.62347538  9.62347538]

Vektor eigen dari Matriks A = [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]

Nilai eigen dari Matriks B = [1.8074176 7.1925824]

Vektor eigen dari Matriks B = [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]
